// AUTO-GENERATED by scripts/embed-ui.ts — do not edit by hand.
import a0 from "../../ui/dist/assets/index-B2WlfUNr.css" with { type: "file" };
import a1 from "../../ui/dist/assets/index-D1NmC4tU.js" with { type: "file" };
import a2 from "../../ui/dist/index.html" with { type: "file" };

export const hasUI = true;
export const assets: Record<string, string> = {
  "/assets/index-B2WlfUNr.css": a0,
  "/assets/index-D1NmC4tU.js": a1,
  "/index.html": a2,
};
