/**
 * Generates server/src/ui-assets.generated.ts from the built UI in ui/dist.
 * Each file is imported with `{ type: "file" }` so `bun build --compile`
 * embeds it into the single executable and gives a runtime-readable path.
 *
 * Run after `vite build`. Invoked by the `build:exe` script.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const here = import.meta.dir; // server/scripts
const serverSrc = join(here, "..", "src");
const distDir = join(here, "..", "..", "ui", "dist");

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

let files: string[] = [];
try {
  files = walk(distDir);
} catch {
  console.error(`Brak ${distDir}. Najpierw zbuduj UI: bun run build:ui`);
  process.exit(1);
}

const imports: string[] = [];
const entries: string[] = [];
files.forEach((abs, i) => {
  const importPath = "../../ui/dist/" + relative(distDir, abs).split("\\").join("/");
  const urlPath = "/" + relative(distDir, abs).split("\\").join("/");
  imports.push(`import a${i} from ${JSON.stringify(importPath)} with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: a${i},`);
});

const content = `// AUTO-GENERATED by scripts/embed-ui.ts — do not edit by hand.
${imports.join("\n")}

export const hasUI = true;
export const assets: Record<string, string> = {
${entries.join("\n")}
};
`;

writeFileSync(join(serverSrc, "ui-assets.generated.ts"), content);
console.log(`Osadzono ${files.length} plików UI do ui-assets.generated.ts`);
